version: '3.9'
services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_PASSWORD: root
    ports:
      - '3306:3306'
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      frx:
  users:
    container_name: users
    depends_on:
      - db
    build:
      context: .
      dockerfile: Dockerfile.dev
    env_file:
      - .env
    ports:
      - 3000:3000
    volumes:
      - /users/node_modules
      - .:/users
    command: "npm run start-api"
    networks:
      frx:
    links:
      - db:db

networks:
  frx:
    external: true
volumes:
  dbdata:
