version: '3.9'
services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: test
      MYSQL_USER: user
      MYSQL_PASSWORD: 123456
    ports:
      - '3306:3306'
    volumes:
      - dbdata:/var/lib/mysql
    #command: --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "db" ]
      timeout: 5s
      retries: 10
    networks:
      frx:
  users:
    container_name: users
    depends_on:
      db:
        condition: service_healthy
    build:
      context: .
      dockerfile: Dockerfile.dev
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_NAME=test
      - DB_USERNAME=user
      - DB_PASSWORD=12345
      - PORT=3000
    ports:
      - 3000:3000
    volumes:
      - /users/node_modules
      - .:/users
    command: "npm run start-api"
    networks:
      frx:
    links:
      - db:db

networks:
  frx:
    external: true
volumes:
  dbdata:
